### ISSUE TITLE
How do you calibrate the camera intrinsic parameters?

### ISSUE THREAD

**Issue by arjunskumar** [HITSZ-NRSL/lidar_camera_calibrator#1]

**Comment by yanliang-wang** [comment]
@arjunskumar Thank you for your interest in this project.

**In this project, the camera's intrinsic parameters are assumed to be known**. There are many commonly used camera intrinsic calibration tools I tested, such as the [ROS camera calibration package](http://wiki.ros.org/camera_calibration), [kalibr](https://github.com/ethz-asl/kalibr) and [Matlab calibration toolbox](https://www.mathworks.com/help/vision/camera-calibration.html). And they work very well.

Hope it helps you!
