### ISSUE TITLE
How to choose apriltag

### ISSUE THREAD

**Issue by wang6342** [HITSZ-NRSL/lidar_camera_calibrator#4]
Hi
First of all, thank you very much for your calibration method and software.
I would like to ask which series of AprilTag you are using.Can you provide the original AprilTag image of your choice or tell me the model number?
I'm using tag36h11, do other images from the series work fine.Since the resolution of the original apriltag image is relatively small, what is the image resolution of the calibration plate of the 80×80cm calibration plate?

Thank you very much
xiao wang

**Comment by yanliang-wang** [comment]
Sorry to reply to you too late.

Yes, I am using the tag36h11 series in the code, you can change it in the code if you use another series.

I have a tag36h11 image with 1024x1024 resolution, which I think is enough for an 80x80cm calibration board. If you think it's not enough, you can use some tool to convert png to SVG.


![tag16_05_00001](https://user-images.githubusercontent.com/35984711/178661962-13e24764-5284-4533-ae32-25ffe9555d16.png)

**Comment by wang6342** [comment]
thank you for your reply！

I downloaded all Apriltag series, including tag36h11.But the image was not found.This morning, I stumbled across its 001 image on the tag16h5 system.

I searched for some methods to generate high-definition images, but the first one below was not configured successfully. Please tell me which method you used to generate this high-definition image.

Thanks again！

**Comment by wang6342** [comment]
https://blog.csdn.net/weixin_42534045/article/details/121677949

**Comment by yanliang-wang** [comment]
That looks to make sense. 👍

**Comment by wang6342** [comment]
Thanks, then I won't bother you.
